export const AZURE_TRANSLATOR_KEY = import.meta.env.VITE_AZURE_TRANSLATOR_KEY;
export const AZURE_TRANSLATOR_REGION = import.meta.env.VITE_AZURE_TRANSLATOR_REGION;
export const AZURE_TRANSLATOR_ENDPOINT = import.meta.env.VITE_AZURE_TRANSLATOR_ENDPOINT;
